// Copyright 2024 The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TrainJobTrainerStatusApplyConfiguration represents a declarative configuration of the TrainJobTrainerStatus type for use
// with apply.
//
// TrainJobTrainerStatus represents the latest known progress and metrics of the Trainer part of the TrainJob.
type TrainJobTrainerStatusApplyConfiguration struct {
	// progressPercentage gives an estimate of how complete the TrainJob is as a percentage.
	// The value will be between 0 and 100, or empty if unknown.
	ProgressPercentage *int32 `json:"progressPercentage,omitempty"`
	// estimatedRemainingSeconds gives the estimated remaining training time in seconds
	// before the train job is completed.
	// The value will be empty if it is unknown.
	EstimatedRemainingSeconds *int32 `json:"estimatedRemainingSeconds,omitempty"`
	// metrics contains the current metrics for the model.
	Metrics []MetricApplyConfiguration `json:"metrics,omitempty"`
	// lastUpdatedTime is the timestamp when these metrics were observed.
	LastUpdatedTime *v1.Time `json:"lastUpdatedTime,omitempty"`
}

// TrainJobTrainerStatusApplyConfiguration constructs a declarative configuration of the TrainJobTrainerStatus type for use with
// apply.
func TrainJobTrainerStatus() *TrainJobTrainerStatusApplyConfiguration {
	return &TrainJobTrainerStatusApplyConfiguration{}
}

// WithProgressPercentage sets the ProgressPercentage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProgressPercentage field is set to the value of the last call.
func (b *TrainJobTrainerStatusApplyConfiguration) WithProgressPercentage(value int32) *TrainJobTrainerStatusApplyConfiguration {
	b.ProgressPercentage = &value
	return b
}

// WithEstimatedRemainingSeconds sets the EstimatedRemainingSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EstimatedRemainingSeconds field is set to the value of the last call.
func (b *TrainJobTrainerStatusApplyConfiguration) WithEstimatedRemainingSeconds(value int32) *TrainJobTrainerStatusApplyConfiguration {
	b.EstimatedRemainingSeconds = &value
	return b
}

// WithMetrics adds the given value to the Metrics field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Metrics field.
func (b *TrainJobTrainerStatusApplyConfiguration) WithMetrics(values ...*MetricApplyConfiguration) *TrainJobTrainerStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMetrics")
		}
		b.Metrics = append(b.Metrics, *values[i])
	}
	return b
}

// WithLastUpdatedTime sets the LastUpdatedTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastUpdatedTime field is set to the value of the last call.
func (b *TrainJobTrainerStatusApplyConfiguration) WithLastUpdatedTime(value v1.Time) *TrainJobTrainerStatusApplyConfiguration {
	b.LastUpdatedTime = &value
	return b
}
